### ISSUE TITLE
Error: Origin null is not allowed by Access-Control-Allow-Origin. 

### ISSUE THREAD

**Issue by michaeltse** [kenyee/angularjs-cart#1]
I run default.htm and able to saw the banner only, but then the console shows "Origin null is not allowed by Access-Control-Allow-Origin. " Any advice please?

**Comment by kenyee** [comment]
This is a quirk w/ how Chrome handles local files that do AJAX requests.  You can put the files on a web server or use firefox as a workaround.  Or if you want to keep using Chrome, add a command line parameter:
  http://stackoverflow.com/questions/5224017/origin-null-is-not-allowed-by-access-control-allow-origin-in-chrome-why
